server:
  port: 8080

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: MYSQL
    show_sql: true
    open-in-view: false
    generate-ddl: true    
    hibernate:
#      ddl-auto: create-drop
#      ddl-auto: update
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
  datasource:
    url: jdbc:mysql://hack-korea.ciupdguewbyc.ap-northeast-1.rds.amazonaws.com:3306/hack-korea
    name:
    username: admin
    password: admin1234

  mvc:
    favicon:
      enabled: false

